apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: email:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: email-secret
