apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: go-app
stringData:
  APP_NAME: "auth"
  APP_ENV: "production"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
  DB_DRIVER: "mysql"
  DB_HOST: "mysql-auth"
  DB_PORT: "3306"
  DB_DATABASE: "auth"
  DB_USERNAME: "auth"
  DB_PASSWORD: "auth"
  DB_LOCAL_MAX_IDLE_CONNECTIONS: "10"
  DB_LOCAL_MAX_OPEN_CONNECTIONS: "100"
  LOG_DRIVER: "stdout"
  LOG_PATH: ""
  LOG_LEVEL: "info"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "auth"
  REDIS_DATABASE: "0"
  AUTH_JWT_SECRET: "secret"
  AUTH_ACCESS_TOKEN_EXPIRE: "15"
  AUTH_REFRESH_TOKEN_EXPIRE: "10080"
  AUTH_EMAIL_VERIFICATION_EXPIRE: "60"
  AUTH_FRONTEND_URL: ""
  KAFKA_BROKERS: "kafka:9092"
