apiVersion: v1
kind: Secret
metadata:
  name: broadcasting-secret
  namespace: go-app
stringData:
  APP_NAME: "broadcasting"
  APP_ENV: "production"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8082"
  LOG_DRIVER: "stdout"
  LOG_PATH: ""
  LOG_LEVEL: "info"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  RABBITMQ_PREFETCH_COUNT: "100"
