apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: go-app
stringData:
  APP_NAME: "email"
  APP_ENV: "production"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8081"
  DB_DRIVER: "mysql"
  DB_HOST: "mysql-email"
  DB_PORT: "3306"
  DB_DATABASE: "email"
  DB_USERNAME: "email"
  DB_PASSWORD: "email"
  DB_MAX_IDLE_CONNECTIONS: "25"
  DB_MAX_OPEN_CONNECTIONS: "25"
  LOG_DRIVER: "stdout"
  LOG_PATH: ""
  LOG_LEVEL: "info"
  MAIL_HOST: "mailpit"
  MAIL_PORT: "1025"
  MAIL_USER: ""
  MAIL_PASSWORD: ""
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_REBALANCE_TIMEOUT_MS: "30000"
  KAFKA_WORKER_POOL_SIZE: "50"
