apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: go-app
stringData:
  MYSQL_ROOT_PASSWORD: "password"
  AUTH_DB_DATABASE: "auth"
  AUTH_DB_USERNAME: "auth"
  AUTH_DB_PASSWORD: "auth"
  EMAIL_DB_DATABASE: "email"
  EMAIL_DB_USERNAME: "email"
  EMAIL_DB_PASSWORD: "email"
